//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaOy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public string Postnro { get; set; }
        public string Postplace { get; set; }
    }
}
